### ISSUE TITLE
FE - Header component - mobile view - make static

### ISSUE THREAD

**Issue by sonjide** [cyf-djla/cyf-student-register#185]
Make the header component fixed, sticky, visible on-top at all times. 

As a user I want to be able to click on the header when I am scroll down the mobile app.

**Comment by sonjide** [comment]
here is an example of sticky header : https://www.loom.com/share/2b3e0b3655324cc1ba96d3e3a101a97c

**Comment by sonjide** [comment]
https://www.w3schools.com/howto/howto_js_sticky_header.asp

**Comment by 12shussein** [comment]
Desktop and mobile view header is now sticky and static. Now user can scroll down and still be able to view the header

**Comment by 12shussein** [comment]
Sonjide has now approved
