### ISSUE TITLE
TOP Priority - Mobile - Burger menu - fix 

### ISSUE THREAD

**Issue by sonjide** [cyf-djla/cyf-student-register#191]
The burger menu component needs to visible in the header, with out error - see image. 

The text should be 
- Home
- Sign Out
- About

**Comment by sonjide** [comment]
![image](https://user-images.githubusercontent.com/94566648/222933595-8423ae72-b268-430b-8b20-999e3faf6436.png)

**Comment by Lunamzelo** [comment]
I have changed the burger menu see picture and  I have changed the text from Main Menu to Home. ready for review.
![Screenshot from 2023-03-06 21-46-12](https://user-images.githubusercontent.com/105117047/223244403-f32c546f-f59f-4d73-ab5a-ae71e813da7e.png)
Approved by Sonjide.

**Comment by Lunamzelo** [comment]
Hamburger menu fixed for all mobile view.
